apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ""
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  spec:
    channel: stable
    config:
      env:
      - name: KVM_EMULATION
        value: "true"
    installPlanApproval: Manual
    name: kubevirt-hyperconverged
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubevirt-hyperconverged-operator.v4.19.6
  status: {}
- apiVersion: hco.kubevirt.io/v1beta1
  kind: HyperConverged
  metadata:
    annotations:
      deployOVS: "false"
    labels:
      app: kubevirt-hyperconverged
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  spec:
    applicationAwareConfig:
      allowApplicationAwareClusterResourceQuota: false
      vmiCalcConfigName: DedicatedVirtualResources
    certConfig:
      ca:
        duration: 48h0m0s
        renewBefore: 24h0m0s
      server:
        duration: 24h0m0s
        renewBefore: 12h0m0s
    deployVmConsoleProxy: false
    enableApplicationAwareQuota: false
    enableCommonBootImageImport: true
    evictionStrategy: None
    featureGates:
      alignCPUs: false
      deployKubeSecondaryDNS: false
      disableMDevConfiguration: false
      downwardMetrics: false
      persistentReservation: false
    higherWorkloadDensity:
      memoryOvercommitPercentage: 100
    infra: {}
    liveMigrationConfig:
      allowAutoConverge: false
      allowPostCopy: false
      completionTimeoutPerGiB: 150
      parallelMigrationsPerCluster: 5
      parallelOutboundMigrationsPerNode: 2
      progressTimeout: 150
    resourceRequirements:
      vmiCPUAllocationRatio: 10
    uninstallStrategy: BlockUninstallIfWorkloadsExist
    virtualMachineOptions:
      disableFreePageReporting: false
      disableSerialConsoleLog: false
    workloadUpdateStrategy:
      batchEvictionInterval: 1m0s
      batchEvictionSize: 10
      workloadUpdateMethods:
      - LiveMigrate
    workloads: {}
  status: {}
