apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ""
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
  spec:
    channel: stable
    config:
      env:
      - name: KVM_EMULATION
        value: "true"
    installPlanApproval: Automatic
    name: kubevirt-hyperconverged
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubevirt-hyperconverged-operator.v4.19.6
  status: {}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/machine-deletion-remediation.openshift-workload-availability: ""
    name: machine-deletion-remediation
    namespace: openshift-workload-availability
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: machine-deletion-remediation
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: machine-deletion-remediation.v0.4.1
  status: {}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/node-healthcheck-operator.openshift-workload-availability: ""
    name: node-healthcheck-operator
    namespace: openshift-workload-availability
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: node-healthcheck-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: node-healthcheck-operator.v0.10.0
  status: {}
kind: List
metadata:
  resourceVersion: ""
